---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role

metadata:
  name: gitlab-runner
  labels:
    app.kubernetes.io/name: gitlab-runner
    app.kubernetes.io/component: runner

rules:
  - apiGroups:
      - ""
    resources:
      - "*"
    verbs:
      - "*"

...
