---
apiVersion: v1
kind: Service

metadata:
  name: gitlab-runner
  labels:
    app.kubernetes.io/name: gitlab-runner
    app.kubernetes.io/component: runner

spec:
  selector:
    app.kubernetes.io/name: gitlab-runner
    app.kubernetes.io/component: runner

  ports:
    - name: metrics
      port: 9252

...
